services:
  - type: web
    name: analyse-cloture-v3
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: credentials.json
      - key: TELEGRAM_TOKEN
        value: "8415756245:AAHaU2KBRsC3q05eLld2JjMt_V7S9j-o4ys"
      - key: TELEGRAM_CHAT_ID
        value: "5814604646"
