services:
  - type: web
    name: analyse-cloture-v3
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
    secretFiles:
      - name: credentials.json
        mountPath: /etc/secrets/credentials.json
