services:
  - type: web
    name: analyse-cloture-v3
    runtime: python
    pythonVersion: 3.13
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_CREDS_PATH
        value: /etc/secrets/credentials.json
    secretFiles:
      - path: /etc/secrets/credentials.json
        envVarName: GOOGLE_CREDS_JSON
