services:
  - type: web
    name: analyse-cloture-v3
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: GOOGLE_SHEET_ID
        value: 1-hPKh5yJq6F-eboLbsG8sLxwdesI9LPH2L08emI7i6g
      - key: TELEGRAM_TOKEN
        value: 6500937161:AAFChZ1ApI6Ud5ySRJzjMJpNVkWo8MKmSxU
      - key: TELEGRAM_CHAT_ID
        value: -4180243604
