services:
  - type: web
    name: analyse-cloture-v3
    plan: free
    runtime: python
    pythonVersion: 3.10.13
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_CREDS_PATH
        value: /etc/secrets/credentials.json
      - key: GOOGLE_CREDS_JSON
        value: /etc/secrets/credentials.json
    secretFiles:
      - path: /etc/secrets/credentials.json
        envVarName: GOOGLE_CREDS_JSON
