services:
  - type: web
    name: analyse-cloture-v3
    runtime: python
    pythonVersion: 3.10.13
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    buildCommand: pip install --upgrade pip wheel setuptools && pip install -r requirements.txt
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
    secrets:
      - source: credentials.json
        target: /etc/secrets/credentials.json
