services:
  - type: web
    name: analyse-cloture-v3
    runtime: python
    buildCommand: >
      PIP_ONLY_BINARY=:all: pip install --upgrade pip setuptools wheel &&
      PIP_ONLY_BINARY=:all: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
    secrets:
      - source: credentials.json
        target: /etc/secrets/credentials.json
