services:
  - type: web
    name: Analyse_cloture_V3
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: TELEGRAM_TOKEN
        fromDotEnv: true
      - key: CHAT_ID
        fromDotEnv: true
      - key: GOOGLE_SHEET_ID
        fromDotEnv: true
