services:
  - type: web
    name: analyse-cloture
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: 8415756245:AAHaU2KBRsC3q05eLld2JjMt_V7S9j-o4ys
        sync: false
      - key: 5814604646
        sync: false
      - key: 1-hPKh5yJq6F-eboLbsG8sLxwdesI9LPH2L08emI7i6g
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
